import {
  IsNotEmpty,
  IsString,
  IsOptional,
  IsDateString,
  IsNumber,
  Min,
  Length,
  IsNumberString,
} from 'class-validator';

export class CreateEmployeeDto {
  // employeeCode is now auto-generated by the backend
  @IsString()
  @IsOptional()
  employeeCode?: string;

  @IsString()
  @IsNotEmpty()
  fullName: string;

  @IsString()
  @IsOptional()
  phone?: string;

  @IsString()
  @IsOptional()
  address?: string;

  @IsDateString()
  @IsOptional()
  birthDate?: string;

  @IsString()
  @IsOptional()
  @Length(12, 12, { message: 'Identity Card must be exactly 12 digits' })
  @IsNumberString({}, { message: 'Identity Card must contain only numbers' })
  identityCard?: string;

  @IsString()
  @IsOptional()
  position?: string;

  @IsNumber()
  @IsOptional()
  @Min(0, { message: 'Salary must be a positive number' })
  salary?: number;

  @IsNumber()
  @IsOptional()
  userId?: number;
}
