export enum Permission {
  // --- USER PERMISSIONS ---
  USER_VIEW_ALL = 'USER_VIEW_ALL',
  USER_VIEW_ID = 'USER_VIEW_ID',
  USER_DELETE = 'USER_DELETE',
  USER_MANAGE = 'USER_MANAGE',

  // --- PRODUCT PERMISSIONS ---
  PRODUCT_VIEW_ALL = 'PRODUCT_VIEW_ALL',
  PRODUCT_VIEW_ID = 'PRODUCT_VIEW_ID',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_APPROVE = 'PRODUCT_APPROVE',

  // --- ORDER PERMISSIONS ---
  ORDER_VIEW_ALL = 'ORDER_VIEW_ALL',
  ORDER_VIEW_ID = 'ORDER_VIEW_ID',
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_DELETE = 'ORDER_DELETE',
  ORDER_CANCEL = 'ORDER_CANCEL',

  // --- INVOICE PERMISSIONS ---
  INVOICE_VIEW_ALL = 'INVOICE_VIEW_ALL',
  INVOICE_VIEW_ID = 'INVOICE_VIEW_ID',
  INVOICE_PAY = 'INVOICE_PAY',
  INVOICE_CANCEL = 'INVOICE_CANCEL',

  // --- OTHER PERMISSIONS ---
  SETTING_MANAGE = 'SETTING_MANAGE',
  LOG_VIEW_ALL = 'LOG_VIEW_ALL',

  // --- EMPLOYEE PERMISSIONS ---
  EMPLOYEE_VIEW_ALL = 'EMPLOYEE_VIEW_ALL',
  EMPLOYEE_VIEW_ID = 'EMPLOYEE_VIEW_ID',
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE = 'EMPLOYEE_DELETE',
  EMPLOYEE_APPROVE = 'EMPLOYEE_APPROVE',

  // --- AREA PERMISSIONS ---
  AREA_VIEW_ALL = 'AREA_VIEW_ALL',
  AREA_VIEW_ID = 'AREA_VIEW_ID',
  AREA_CREATE = 'AREA_CREATE',
  AREA_UPDATE = 'AREA_UPDATE',
  AREA_DELETE = 'AREA_DELETE',
  AREA_APPROVE = 'AREA_APPROVE',

  // --- TABLE PERMISSIONS ---
  TABLE_VIEW_ALL = 'TABLE_VIEW_ALL',
  TABLE_VIEW_ID = 'TABLE_VIEW_ID',
  TABLE_CREATE = 'TABLE_CREATE',
  TABLE_UPDATE = 'TABLE_UPDATE',
  TABLE_DELETE = 'TABLE_DELETE',
  TABLE_APPROVE = 'TABLE_APPROVE',

  // --- APPROVAL PERMISSIONS ---
  APPROVAL_VIEW_ALL = 'APPROVAL_VIEW_ALL',
  APPROVAL_VIEW_ID = 'APPROVAL_VIEW_ID',
  APPROVAL_CREATE = 'APPROVAL_CREATE',
  APPROVAL_UPDATE = 'APPROVAL_UPDATE',
  APPROVAL_DELETE = 'APPROVAL_DELETE',
  APPROVAL_APPROVE = 'APPROVAL_APPROVE',
  APPROVAL_MANAGE = 'APPROVAL_MANAGE',

  // --- ROLE PERMISSIONS ---
  ROLE_VIEW_ALL = 'ROLE_VIEW_ALL',
  ROLE_VIEW_ID = 'ROLE_VIEW_ID',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  // --- STATISTICS PERMISSIONS ---
  STATISTICS_VIEW_ALL = 'STATISTICS_VIEW_ALL',
  STATISTICS_EXPORT = 'STATISTICS_EXPORT',

  // --- AI ASSISTANT PERMISSIONS ---
  AI_ASSISTANT_CHAT = 'AI_ASSISTANT_CHAT',
  AI_ASSISTANT_MANAGE = 'AI_ASSISTANT_MANAGE',

  // --- DASHBOARD PERMISSIONS ---
  DASHBOARD_VIEW_ALL = 'DASHBOARD_VIEW_ALL',

  // --- CATEGORY PERMISSIONS ---
  CATEGORY_VIEW_ALL = 'CATEGORY_VIEW_ALL',
  CATEGORY_VIEW_ID = 'CATEGORY_VIEW_ID',
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_UPDATE = 'CATEGORY_UPDATE',
  CATEGORY_DELETE = 'CATEGORY_DELETE',
  CATEGORY_APPROVE = 'CATEGORY_APPROVE',

  // --- LOGGING PERMISSIONS ---
  LOGGING_VIEW_ALL = 'LOGGING_VIEW_ALL',
}
